from __future__ import annotations

import json
from typing import Any

from langchain_core.runnables import RunnableConfig
from langfuse import observe

from src.app.graph.state import AgentState
from src.app.prompts.renderer import render_prompt
from src.app.schemas import CritiqueSchema
from src.infra.llm.client import get_llm_client

llm_client = get_llm_client()


@observe()
async def critic_node(state: AgentState, config: RunnableConfig) -> dict[str, Any]:
    """
    Reviews the plan generated by the implementation agent.
    """
    configurable = config.get("configurable", {})
    _ = configurable.get("db_session")
    messages = state["messages"]
    user_id = state.get("user_id")

    plan = state.get("plan")
    plan_data: dict[str, Any]
    if plan is not None and hasattr(plan, "model_dump"):
        plan_data = plan.model_dump()
    elif isinstance(plan, dict):
        plan_data = plan
    else:
        plan_data = {}

    system_prompt = render_prompt(
        "critic", user_id=user_id, plan_json=json.dumps(plan_data)
    )

    critique = await llm_client.generate(
        system_prompt=system_prompt,
        messages=messages,
        schema=CritiqueSchema,
    )

    return {
        "last_agent": "critic",
        "step_count": state["step_count"] + 1,
        "critique": critique,
    }
