from typing import Any

from src.app.graph.state import AgentState
from src.app.schemas import CritiqueSchema
from src.infra.llm.client import get_llm_client

llm_client = get_llm_client()


async def critic_node(state: AgentState) -> dict[str, Any]:
    """
    Reviews the plan generated by the implementation agent.
    """
    messages = state["messages"]

    critique = await llm_client.generate(
        system_prompt="You are a Critic. Review the plan...",
        messages=messages,
        schema=CritiqueSchema,
    )

    return {
        "last_agent": "critic",
        "step_count": state["step_count"] + 1,
        "critique": critique,
    }
